class_name ResearchData extends Resource

enum researchIDs {
	UNLOCK_BORE, # Nanite Bore unlock
	
	FOUNDRY_NANITES, # Nanite production in Foundries
	BASIC_CIRCUIT, # Basic Circuit production
	
	LOGISTICS_1,
	LOGISTICS_2,
	LOGISTICS_3,
	LOGISTICS_4,
	LOGISTICS_5,
	LOGISTICS_6,
	LOGISTICS_7,
	LOGISTICS_8,
	LOGISTICS_9,
	LOGISTICS_10,
	
	CONSTRUCTION_1,
	CONSTRUCTION_2,
	CONSTRUCTION_3,
	CONSTRUCTION_4,
	CONSTRUCTION_5,
	CONSTRUCTION_6,
	CONSTRUCTION_7,
	CONSTRUCTION_8,
	CONSTRUCTION_9,
	CONSTRUCTION_10
}
