class_name ResourceData extends Resource

enum resourceID {
	SCRAP,
	NANITES,
	BASIC_PLATES,
	BASIC_CIRCUITS,
	
	CRAFTING_RESEARCH,
	BUILDING_RESEARCH,
	FIGHTING_RESEARCH,
	CORRUPTION_RESEARCH,
	STRANGE_RESEARCH
}
